<a href="https://colab.research.google.com/github/sujan6539/ml/blob/main/ML_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing torch
import torch

In [5]:
# creating tensors

#1
t1= torch.tensor([[1,2,3],[3,4,5], [5,6,7]])
t1

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [4]:
#2
t2 = torch.ones(3,5)
t2

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [8]:
#3
t3 = torch.zeros(3,5)
t3

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
#4  Create a tensor with random  values drawn from standard Gaussian distribution(normal) with mean = 0 and Standard deviation = 1
t4 = torch.randn(2,4)
t4

tensor([[-1.3482, -0.7614,  0.8346, -1.5685],
        [ 0.7608,  0.3691,  0.9311,  0.7235]])

In [29]:
#5
t5 = torch.arange(25)
t5

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [45]:
# Reshape
# -1 takes the inferred size; ie: it takes the number of rows after distributin
# element to the number of columns provided.
t5 = t5.reshape(-1,5)
t5

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [44]:
t5.shape

torch.Size([5, 5])

In [49]:
# Slicing
"""
[start in row: stop in row , start in col : stop in col], excludes end value
"""
s5 = t5[1:4, 2:4]
s5

tensor([[ 7,  8],
        [12, 13],
        [17, 18]])

In [59]:
a = torch.arange(6)

b = torch.arange(6)



In [60]:
a


tensor([0, 1, 2, 3, 4, 5])

In [61]:
b

tensor([0, 1, 2, 3, 4, 5])

In [76]:
a = a.reshape(-1,1)
a

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])

In [85]:
b = b.reshape(-1,3)
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [78]:
b.shape

torch.Size([1, 6])

In [80]:
a+b

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5,  6],
        [ 2,  3,  4,  5,  6,  7],
        [ 3,  4,  5,  6,  7,  8],
        [ 4,  5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9, 10]])